package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// GetCompetition is the resolver for the getCompetition field.
func (r *queryResolver) GetCompetition(ctx context.Context, input string) (*model.Competition, error) {
	panic(fmt.Errorf("not implemented: GetCompetition - getCompetition"))
}
