package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph/graphconverters"
	graphmodels "github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// CreateCompetition is the resolver for the createCompetition field.
func (r *mutationResolver) CreateCompetition(ctx context.Context, input graphmodels.CompetitionInput) (*graphmodels.Competition, error) {
	panic(fmt.Errorf("not implemented: CreateCompetition - createCompetition"))
}

// GetCompetition is the resolver for the getCompetition field.
func (r *queryResolver) GetCompetition(ctx context.Context, input string) (*graphmodels.Competition, error) {
	competition, err := r.Competition.GetCompetition(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("getting competition: %w", err)
	}

	return graphconverters.ConvertModelCompetitionToGraphCompetition(competition), nil
}
