package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// CreateEntry is the resolver for the createEntry field.
func (r *mutationResolver) CreateEntry(ctx context.Context, input model.CreateEntryInput) (*model.Entry, error) {
	panic(fmt.Errorf("not implemented: CreateEntry - createEntry"))
}

// UpdateEntry is the resolver for the updateEntry field.
func (r *mutationResolver) UpdateEntry(ctx context.Context, input model.UpdateEntryInput) (*model.Entry, error) {
	panic(fmt.Errorf("not implemented: UpdateEntry - updateEntry"))
}

// GetEntry is the resolver for the getEntry field.
func (r *queryResolver) GetEntry(ctx context.Context, input string) (*model.Entry, error) {
	panic(fmt.Errorf("not implemented: GetEntry - getEntry"))
}
