package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Empty is the resolver for the _empty field.
func (r *queryResolver) Empty(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Mutation returns subgraph.MutationResolver implementation.
func (r *Resolver) Mutation() subgraph.MutationResolver { return &mutationResolver{r} }

// Query returns subgraph.QueryResolver implementation.
func (r *Resolver) Query() subgraph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
