package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph"
	graphmodels "github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// Competition is the resolver for the competition field.
func (r *roundResolver) Competition(ctx context.Context, obj *graphmodels.Round) (*graphmodels.Competition, error) {
	panic(fmt.Errorf("not implemented: Competition - competition"))
}

// Round returns subgraph.RoundResolver implementation.
func (r *Resolver) Round() subgraph.RoundResolver { return &roundResolver{r} }

type roundResolver struct{ *Resolver }
