package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph"
	"github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	user, err := r.User.CreateUser(ctx, input)
	if err != nil {
		fmt.Printf("application error: %+v\n", err)
		return &model.User{}, fmt.Errorf("creating user: %w", err)
	}

	return &model.User{
		ID:          user.ID,
		Username:    user.Username,
		FirstName:   user.FirstName,
		LastName:    user.LastName,
		Email:       user.Email,
		PhoneNumber: user.PhoneNumber,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, input string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// CreateCompetition is the resolver for the createCompetition field.
func (r *mutationResolver) CreateCompetition(ctx context.Context, input model.CompetitionInput) (*model.Competition, error) {
	panic(fmt.Errorf("not implemented: CreateCompetition - createCompetition"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, input string) (*model.User, error) {
	user, err := r.User.GetUser(ctx, input)
	if err != nil {
		fmt.Printf("application error: %+v\n", err)
		return &model.User{}, fmt.Errorf("getting user: %w", err)
	}

	return &model.User{
		ID:          user.ID,
		Username:    user.Username,
		FirstName:   user.FirstName,
		LastName:    user.LastName,
		Email:       user.Email,
		PhoneNumber: user.PhoneNumber,
	}, nil
}

// ListUsers is the resolver for the ListUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: ListUsers - ListUsers"))
}

// GetCompetition is the resolver for the getCompetition field.
func (r *queryResolver) GetCompetition(ctx context.Context, input string) (*model.Competition, error) {
	panic(fmt.Errorf("not implemented: GetCompetition - getCompetition"))
}

// Mutation returns subgraph.MutationResolver implementation.
func (r *Resolver) Mutation() subgraph.MutationResolver { return &mutationResolver{r} }

// Query returns subgraph.QueryResolver implementation.
func (r *Resolver) Query() subgraph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
