package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	graphmodels "github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// CreateSelection is the resolver for the createSelection field.
func (r *mutationResolver) CreateSelection(ctx context.Context, input graphmodels.CreateSelectionInput) (*graphmodels.Selection, error) {
	panic(fmt.Errorf("not implemented: CreateSelection - createSelection"))
}

// ChangeSelection is the resolver for the changeSelection field.
func (r *mutationResolver) ChangeSelection(ctx context.Context, input graphmodels.ChangeSelectionInput) (*graphmodels.Selection, error) {
	panic(fmt.Errorf("not implemented: ChangeSelection - changeSelection"))
}

// UpdateSelection is the resolver for the updateSelection field.
func (r *mutationResolver) UpdateSelection(ctx context.Context, input graphmodels.UpdateSelectionInput) (*graphmodels.Selection, error) {
	panic(fmt.Errorf("not implemented: UpdateSelection - updateSelection"))
}

// GetSelection is the resolver for the getSelection field.
func (r *queryResolver) GetSelection(ctx context.Context, input string) (*graphmodels.Selection, error) {
	panic(fmt.Errorf("not implemented: GetSelection - getSelection"))
}
