package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph/graphconverters"
	graphmodels "github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// GetTeam is the resolver for the getTeam field.
func (r *queryResolver) GetTeam(ctx context.Context, input string) (*graphmodels.Team, error) {
	team, err := r.TeamService.GetTeam(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("getting team: %w", err)
	}

	return graphconverters.ConvertModelTeamToGraphTeam(team), nil
}

// ListTeams is the resolver for the listTeams field.
func (r *queryResolver) ListTeams(ctx context.Context) ([]*graphmodels.Team, error) {
	teams, err := r.TeamService.ListTeams(ctx)
	if err != nil {
		return nil, fmt.Errorf("listing teams: %w", err)
	}

	return graphconverters.ConvertModelTeamsToGraphTeams(teams), nil
}
