package graphresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/dom-m17/lms/backend/internal/subgraph/model"
)

// GetTeam is the resolver for the getTeam field.
func (r *queryResolver) GetTeam(ctx context.Context, input string) (*model.Team, error) {
	panic(fmt.Errorf("not implemented: GetTeam - getTeam"))
}

// ListTeams is the resolver for the listTeams field.
func (r *queryResolver) ListTeams(ctx context.Context) ([]*model.Team, error) {
	panic(fmt.Errorf("not implemented: ListTeams - listTeams"))
}
