// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Username      string `json:"username"`
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	Email         string `json:"email"`
	PhoneNumber   string `json:"phoneNumber"`
	FavouriteTeam string `json:"favouriteTeam"`
}

type CreateUserResponse struct {
	ID            string `json:"id"`
	Username      string `json:"username"`
	FirstName     string `json:"firstName"`
	LastName      string `json:"lastName"`
	Email         string `json:"email"`
	PhoneNumber   string `json:"phoneNumber"`
	FavouriteTeam string `json:"favouriteTeam"`
}

type Mutation struct {
}

type Query struct {
}
