// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Username       string  `json:"username"`
	HashedPassword string  `json:"hashedPassword"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	PhoneNumber    string  `json:"phoneNumber"`
	FavouriteTeam  *string `json:"favouriteTeam,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID            string  `json:"id"`
	Username      string  `json:"username"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	Email         string  `json:"email"`
	PhoneNumber   string  `json:"phoneNumber"`
	FavouriteTeam *string `json:"favouriteTeam,omitempty"`
}
