// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphmodels

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ChangeSelectionInput struct {
	ID      string `json:"id"`
	MatchID string `json:"matchId"`
	TeamID  string `json:"teamId"`
}

type Competition struct {
	ID            string            `json:"id"`
	Name          string            `json:"name"`
	StartMatchday int32             `json:"startMatchday"`
	Status        CompetitionStatus `json:"status"`
	Rounds        []*Round          `json:"rounds"`
	CreatedAt     time.Time         `json:"createdAt"`
	UpdatedAt     time.Time         `json:"updatedAt"`
}

type CreateCompetitionInput struct {
	Name          string `json:"name"`
	StartMatchday int32  `json:"startMatchday"`
}

type CreateEntryInput struct {
	UserID        string `json:"userId"`
	CompetitionID string `json:"competitionId"`
}

type CreateSelectionInput struct {
	EntryID string `json:"entryId"`
	MatchID string `json:"matchId"`
	TeamID  string `json:"teamId"`
}

type CreateUserInput struct {
	Username       string  `json:"username"`
	HashedPassword string  `json:"hashedPassword"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	DateOfBirth    string  `json:"dateOfBirth"`
	FavouriteTeam  *string `json:"favouriteTeam,omitempty"`
}

type Entry struct {
	ID          string       `json:"id"`
	User        *User        `json:"user"`
	Competition *Competition `json:"competition"`
	Status      EntryStatus  `json:"status"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

type Match struct {
	ID        string      `json:"id"`
	HomeTeam  *Team       `json:"homeTeam"`
	AwayTeam  *Team       `json:"awayTeam"`
	Matchday  int32       `json:"matchday"`
	MatchDate time.Time   `json:"matchDate"`
	HomeGoals *int32      `json:"homeGoals,omitempty"`
	AwayGoals *int32      `json:"awayGoals,omitempty"`
	Status    MatchStatus `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type Round struct {
	ID            string       `json:"id"`
	RoundNumber   int32        `json:"roundNumber"`
	Competition   *Competition `json:"competition"`
	Matchday      int32        `json:"matchday"`
	Status        RoundStatus  `json:"status"`
	EntryDeadline time.Time    `json:"entryDeadline"`
	CreatedAt     time.Time    `json:"CreatedAt"`
	UpdatedAt     time.Time    `json:"UpdatedAt"`
}

type Selection struct {
	ID        string    `json:"id"`
	Entry     *Entry    `json:"entry"`
	Match     *Match    `json:"match"`
	Team      *Team     `json:"team"`
	IsCorrect *bool     `json:"isCorrect,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Team struct {
	ID        string `json:"id"`
	LongName  string `json:"longName"`
	ShortName string `json:"shortName"`
	Tla       string `json:"tla"`
	CrestURL  string `json:"crestUrl"`
}

type UpdateEntryInput struct {
	ID     string      `json:"id"`
	Status EntryStatus `json:"status"`
}

type UpdateSelectionInput struct {
	ID        string `json:"id"`
	IsCorrect *bool  `json:"isCorrect,omitempty"`
}

type UpdateUserInput struct {
	ID            string  `json:"id"`
	Username      string  `json:"username"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	Email         string  `json:"email"`
	PhoneNumber   *string `json:"phoneNumber,omitempty"`
	DateOfBirth   string  `json:"dateOfBirth"`
	FavouriteTeam *string `json:"favouriteTeam,omitempty"`
}

type User struct {
	ID            string    `json:"id"`
	Username      string    `json:"username"`
	FirstName     string    `json:"firstName"`
	LastName      string    `json:"lastName"`
	Email         string    `json:"email"`
	PhoneNumber   *string   `json:"phoneNumber,omitempty"`
	DateOfBirth   string    `json:"dateOfBirth"`
	FavouriteTeam *Team     `json:"favouriteTeam,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type CreateMatchInput struct {
	HomeTeam  string    `json:"homeTeam"`
	AwayTeam  string    `json:"awayTeam"`
	Matchday  int32     `json:"matchday"`
	MatchDate time.Time `json:"matchDate"`
}

type UpdateMatchInput struct {
	HomeGoals int32     `json:"homeGoals"`
	AwayGoals int32     `json:"awayGoals"`
	Matchday  int32     `json:"matchday"`
	MatchDate time.Time `json:"matchDate"`
}

type CompetitionStatus string

const (
	CompetitionStatusOpen       CompetitionStatus = "OPEN"
	CompetitionStatusInProgress CompetitionStatus = "IN_PROGRESS"
	CompetitionStatusComplete   CompetitionStatus = "COMPLETE"
)

var AllCompetitionStatus = []CompetitionStatus{
	CompetitionStatusOpen,
	CompetitionStatusInProgress,
	CompetitionStatusComplete,
}

func (e CompetitionStatus) IsValid() bool {
	switch e {
	case CompetitionStatusOpen, CompetitionStatusInProgress, CompetitionStatusComplete:
		return true
	}
	return false
}

func (e CompetitionStatus) String() string {
	return string(e)
}

func (e *CompetitionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompetitionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompetitionStatus", str)
	}
	return nil
}

func (e CompetitionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompetitionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompetitionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntryStatus string

const (
	EntryStatusActive     EntryStatus = "ACTIVE"
	EntryStatusInProgress EntryStatus = "IN_PROGRESS"
	EntryStatusComplete   EntryStatus = "COMPLETE"
)

var AllEntryStatus = []EntryStatus{
	EntryStatusActive,
	EntryStatusInProgress,
	EntryStatusComplete,
}

func (e EntryStatus) IsValid() bool {
	switch e {
	case EntryStatusActive, EntryStatusInProgress, EntryStatusComplete:
		return true
	}
	return false
}

func (e EntryStatus) String() string {
	return string(e)
}

func (e *EntryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntryStatus", str)
	}
	return nil
}

func (e EntryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchStatus string

const (
	MatchStatusScheduled MatchStatus = "SCHEDULED"
	MatchStatusTimed     MatchStatus = "TIMED"
	MatchStatusInPlay    MatchStatus = "IN_PLAY"
	MatchStatusFinished  MatchStatus = "FINISHED"
)

var AllMatchStatus = []MatchStatus{
	MatchStatusScheduled,
	MatchStatusTimed,
	MatchStatusInPlay,
	MatchStatusFinished,
}

func (e MatchStatus) IsValid() bool {
	switch e {
	case MatchStatusScheduled, MatchStatusTimed, MatchStatusInPlay, MatchStatusFinished:
		return true
	}
	return false
}

func (e MatchStatus) String() string {
	return string(e)
}

func (e *MatchStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchStatus", str)
	}
	return nil
}

func (e MatchStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoundStatus string

const (
	RoundStatusPending  RoundStatus = "PENDING"
	RoundStatusInPlay   RoundStatus = "IN_PLAY"
	RoundStatusFinished RoundStatus = "FINISHED"
)

var AllRoundStatus = []RoundStatus{
	RoundStatusPending,
	RoundStatusInPlay,
	RoundStatusFinished,
}

func (e RoundStatus) IsValid() bool {
	switch e {
	case RoundStatusPending, RoundStatusInPlay, RoundStatusFinished:
		return true
	}
	return false
}

func (e RoundStatus) String() string {
	return string(e)
}

func (e *RoundStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoundStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoundStatus", str)
	}
	return nil
}

func (e RoundStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoundStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoundStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
