// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: match.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    home_team, away_team, matchday, match_date
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, home_team, away_team, matchday, match_date, home_goals, away_goals, has_finished
`

type CreateMatchParams struct {
	HomeTeam  int64              `json:"home_team"`
	AwayTeam  int64              `json:"away_team"`
	Matchday  int32              `json:"matchday"`
	MatchDate pgtype.Timestamptz `json:"match_date"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.HomeTeam,
		arg.AwayTeam,
		arg.Matchday,
		arg.MatchDate,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.Matchday,
		&i.MatchDate,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.HasFinished,
	)
	return i, err
}

const getMatch = `-- name: GetMatch :one
SELECT id, home_team, away_team, matchday, match_date, home_goals, away_goals, has_finished FROM matches
WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id int64) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.Matchday,
		&i.MatchDate,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.HasFinished,
	)
	return i, err
}

const getMatchesByMatchday = `-- name: GetMatchesByMatchday :many
SELECT id, home_team, away_team, matchday, match_date, home_goals, away_goals, has_finished FROM matches
WHERE matchday = $1
`

func (q *Queries) GetMatchesByMatchday(ctx context.Context, matchday int32) ([]Match, error) {
	rows, err := q.db.Query(ctx, getMatchesByMatchday, matchday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.Matchday,
			&i.MatchDate,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.HasFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches 
SET
    matchday = $2,
    match_date = $3,
    home_goals = $4,
    away_goals = $5,
    has_finished = $6
WHERE id = $1
RETURNING id, home_team, away_team, matchday, match_date, home_goals, away_goals, has_finished
`

type UpdateMatchParams struct {
	ID          int64              `json:"id"`
	Matchday    int32              `json:"matchday"`
	MatchDate   pgtype.Timestamptz `json:"match_date"`
	HomeGoals   pgtype.Int4        `json:"home_goals"`
	AwayGoals   pgtype.Int4        `json:"away_goals"`
	HasFinished bool               `json:"has_finished"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.ID,
		arg.Matchday,
		arg.MatchDate,
		arg.HomeGoals,
		arg.AwayGoals,
		arg.HasFinished,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.Matchday,
		&i.MatchDate,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.HasFinished,
	)
	return i, err
}
