// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: competition_match.sql

package db

import (
	"context"
)

const createCompetitionMatch = `-- name: CreateCompetitionMatch :exec
INSERT INTO competition_matches (
    competition_id, match_id
) VALUES (
    $1, $2
)
`

type CreateCompetitionMatchParams struct {
	CompetitionID string `json:"competition_id"`
	MatchID       string `json:"match_id"`
}

func (q *Queries) CreateCompetitionMatch(ctx context.Context, arg CreateCompetitionMatchParams) error {
	_, err := q.db.ExecContext(ctx, createCompetitionMatch, arg.CompetitionID, arg.MatchID)
	return err
}
