// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: competition.sql

package db

import (
	"context"
)

const createCompetition = `-- name: CreateCompetition :one
INSERT INTO competitions (
    name,
    start_matchday
) VALUES (
    $1, $2
)
RETURNING id, name, start_matchday, status, created_at, updated_at
`

type CreateCompetitionParams struct {
	Name          string `json:"name"`
	StartMatchday int32  `json:"start_matchday"`
}

func (q *Queries) CreateCompetition(ctx context.Context, arg CreateCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, createCompetition, arg.Name, arg.StartMatchday)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartMatchday,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetition = `-- name: GetCompetition :one
SELECT id, name, start_matchday, status, created_at, updated_at FROM competitions
WHERE id = $1
`

func (q *Queries) GetCompetition(ctx context.Context, id string) (Competition, error) {
	row := q.db.QueryRowContext(ctx, getCompetition, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartMatchday,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompetitions = `-- name: ListCompetitions :many
SELECT id, name, start_matchday, status, created_at, updated_at FROM competitions
`

func (q *Queries) ListCompetitions(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.QueryContext(ctx, listCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Competition{}
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartMatchday,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
