// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: match.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/dom-m17/lms/backend/internal/models"
)

const getMatch = `-- name: GetMatch :one
SELECT id, home_team_id, away_team_id, matchday, match_date, home_goals, away_goals, status FROM matches
WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Matchday,
		&i.MatchDate,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.Status,
	)
	return i, err
}

const getMatchesByMatchday = `-- name: GetMatchesByMatchday :many
SELECT 
    id AS match_id,
    home_team_id AS home_team_id,
    away_team_id AS away_team_id,
    matchday AS matchday,
    match_date AS match_date,
    home_goals AS home_goals,
    away_goals AS away_goals,
    "status" AS "status"
FROM matches
WHERE matchday = $1
ORDER BY match_date ASC
`

type GetMatchesByMatchdayRow struct {
	MatchID    string             `json:"match_id"`
	HomeTeamID string             `json:"home_team_id"`
	AwayTeamID string             `json:"away_team_id"`
	Matchday   int32              `json:"matchday"`
	MatchDate  time.Time          `json:"match_date"`
	HomeGoals  sql.NullInt32      `json:"home_goals"`
	AwayGoals  sql.NullInt32      `json:"away_goals"`
	Status     models.MatchStatus `json:"status"`
}

func (q *Queries) GetMatchesByMatchday(ctx context.Context, matchday int32) ([]GetMatchesByMatchdayRow, error) {
	rows, err := q.db.QueryContext(ctx, getMatchesByMatchday, matchday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchesByMatchdayRow{}
	for rows.Next() {
		var i GetMatchesByMatchdayRow
		if err := rows.Scan(
			&i.MatchID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Matchday,
			&i.MatchDate,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (
    id, home_team_id, away_team_id, matchday, match_date, home_goals, away_goals, "status"
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) 
ON CONFLICT (id) DO UPDATE
SET home_team_id = EXCLUDED.home_team_id,
    away_team_id = EXCLUDED.away_team_id,
    matchday = EXCLUDED.matchday,
    match_date = EXCLUDED.match_date,
    home_goals = EXCLUDED.home_goals,
    away_goals = EXCLUDED.away_goals,
    "status" = EXCLUDED."status"
RETURNING id, home_team_id, away_team_id, matchday, match_date, home_goals, away_goals, status
`

type UpsertMatchParams struct {
	ID         string             `json:"id"`
	HomeTeamID string             `json:"home_team_id"`
	AwayTeamID string             `json:"away_team_id"`
	Matchday   int32              `json:"matchday"`
	MatchDate  time.Time          `json:"match_date"`
	HomeGoals  sql.NullInt32      `json:"home_goals"`
	AwayGoals  sql.NullInt32      `json:"away_goals"`
	Status     models.MatchStatus `json:"status"`
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, upsertMatch,
		arg.ID,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.Matchday,
		arg.MatchDate,
		arg.HomeGoals,
		arg.AwayGoals,
		arg.Status,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Matchday,
		&i.MatchDate,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.Status,
	)
	return i, err
}
