// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: round.sql

package db

import (
	"context"
)

const getRound = `-- name: GetRound :one
SELECT id, round_number, competition_id, matchday FROM rounds
WHERE id = $1
`

func (q *Queries) GetRound(ctx context.Context, id string) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoundNumber,
		&i.CompetitionID,
		&i.Matchday,
	)
	return i, err
}
